# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['main.py',
            'inc\\connect_window\\Qthread_ping.py',
            'inc\\connect_window\\UI_connect_info.py',
            'inc\\framelesswindow\\__init__.py',
            'inc\\framelesswindow\\frameless_window.py',
            'inc\\packageAngle\\Qthread_package.py',
            'inc\\packageAngle\\UI_packageAngle.py',
            'inc\\port_8056\\Qthread_8056.py',
            'inc\\port_8056\\UI_8056.py',
            'inc\\titlebar\\title_bar_buttons.py',
            'inc\\titlebar\\title_bar.py',
            'inc\\ui2py\\connect_info.py',
            'inc\\ui2py\\packageAngle.py',
            'inc\\ui2py\\port_8056.py',
            'inc\\ui2py\\log_8058.py',
            'inc\\windoweffect\\__init__.py',
            'inc\\windoweffect\\c_structures.py',
            'inc\\windoweffect\\window_effect.py',
            'inc\\xml_widget\\link_xmlWidget.py',
            'inc\\xml_widget\\Qthread_xml.py',
            'inc\\xml_widget\\UI_XmlWidget.py',
            'inc\\log_8058\\Qthread_log_8058.py',
            'inc\\log_8058\\UI_log_8058.py',
            'inc\\__init__.py',
            'inc\\Class_excel.py',
            'inc\\Class_json.py',
            'inc\\Class_sftp.py',
            'inc\\Class_xml.py',
            'inc\\global_value.py',
            'inc\\UI_LeftTabWidget.py'],
             pathex=['E:\\1-Git\\My_Project\\ToolBox'],
             binaries=[],
             datas=[('src\\icon\\*.png','images'),
                    ('src\\images\\*.png','images')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[], 
          runtime_tmpdir=None,
          console=False,
          icon="src\\icon\\ToolBox1.ico")
