# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\1-Git\My_Project\ToolBox\ui\log_8058.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_8058(object):
    def setupUi(self, log_8058):
        log_8058.setObjectName("log_8058")
        log_8058.resize(862, 604)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(log_8058)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(log_8058)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.line = QtWidgets.QFrame(log_8058)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_log = QtWidgets.QTextEdit(log_8058)
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        self.horizontalLayout.addWidget(self.textEdit_log)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_getlog = QtWidgets.QPushButton(log_8058)
        self.btn_getlog.setObjectName("btn_getlog")
        self.verticalLayout.addWidget(self.btn_getlog)
        self.btn_savelog = QtWidgets.QPushButton(log_8058)
        self.btn_savelog.setObjectName("btn_savelog")
        self.verticalLayout.addWidget(self.btn_savelog)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(log_8058)
        QtCore.QMetaObject.connectSlotsByName(log_8058)

    def retranslateUi(self, log_8058):
        _translate = QtCore.QCoreApplication.translate
        log_8058.setWindowTitle(_translate("log_8058", "Form"))
        self.label.setText(_translate("log_8058", "机器人日志"))
        self.btn_getlog.setToolTip(_translate("log_8058", "<html><head/><body><p>从机器人中获取日志</p></body></html>"))
        self.btn_getlog.setText(_translate("log_8058", "获取"))
        self.btn_savelog.setToolTip(_translate("log_8058", "<html><head/><body><p>将日志保存到本地</p></body></html>"))
        self.btn_savelog.setText(_translate("log_8058", "保存"))
